/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintojuego.vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form GUIInterfaz
     */
    public GUIInterfaz() {
        initComponents();
        //setVisible(true);
    }

    public PanelInterfaz getPanelInterfaz1() {
        return panelInterfaz1;
    }

    public void escucharClick(MouseListener controlador) {
        this.addMouseListener(controlador);
    }

    public void escuchar(ActionListener controlador) {
        exit.addActionListener(controlador);
    }
    
    public void escucharTeclado(KeyListener controlador){
    this.addKeyListener(controlador);
    }
    
    public void showMessage(String mensaje){
    JOptionPane.showMessageDialog(null, mensaje);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        panelInterfaz1 = new com.mycompany.laberintojuego.vista.PanelInterfaz();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgP/exit1.png"))); // NOI18N
        exit.setActionCommand("exit");
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 90, 100));

        javax.swing.GroupLayout panelInterfaz1Layout = new javax.swing.GroupLayout(panelInterfaz1);
        panelInterfaz1.setLayout(panelInterfaz1Layout);
        panelInterfaz1Layout.setHorizontalGroup(
            panelInterfaz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        panelInterfaz1Layout.setVerticalGroup(
            panelInterfaz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(panelInterfaz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments //
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIInterfaz().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private com.mycompany.laberintojuego.vista.PanelInterfaz panelInterfaz1;
    // End of variables declaration//GEN-END:variables
}
