/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laberintojuego.vista;

import com.mycompany.laberintojuego.controlador.ControladorJuego;
import com.mycompany.laberintojuego.controlador.ControladorLaberinto;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class PanelInterfaz extends javax.swing.JPanel {

    private ImageIcon fondo;
    private ControladorLaberinto controladorLaberinto;
    private PanelInterfaz panelLaberinto;
//private ControladorJuego controlador;

    /**
     * Creates new form GUIPanelInterfaz
     */
    public PanelInterfaz() {
        initComponents();
        fondo = new ImageIcon("./src/main/resources/imgP/laberinto.png");
    }

    public void setControlador(ControladorLaberinto controlador) {
        this.controladorLaberinto = controlador;
    }

    public void paint(Graphics g) {
        super.paint(g);

        fondo.paintIcon(null, g, 0, 0);

        if (controladorLaberinto != null) {
            controladorLaberinto.dibujar(g);
            

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
